# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-02-25 00:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tag',
            name='posts',
            field=models.ManyToManyField(blank=True, through='posts.PostTag', to='posts.Post'),
        ),
    ]
