# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-24 22:31
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='address',
        ),
        migrations.AddField(
            model_name='userprofile',
            name='hometown',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='posts.City'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='job',
            field=models.CharField(default=datetime.datetime(2016, 2, 24, 22, 31, 15, 993413, tzinfo=utc), max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='userprofile',
            name='school',
            field=models.CharField(default=datetime.datetime(2016, 2, 24, 22, 31, 26, 568485, tzinfo=utc), max_length=50),
            preserve_default=False,
        ),
    ]
