# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-02-21 01:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_auto_20160220_2136'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='house',
            name='subletter',
        ),
        migrations.RemoveField(
            model_name='post',
            name='content',
        ),
        migrations.RemoveField(
            model_name='post',
            name='title',
        ),
        migrations.AddField(
            model_name='house',
            name='baths',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='house',
            name='beds',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='house',
            name='content',
            field=models.TextField(default='', max_length=1000),
        ),
        migrations.AddField(
            model_name='house',
            name='price',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='house',
            name='title',
            field=models.CharField(default='', max_length=100),
        ),
    ]
