# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-02-25 00:30
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_tag_posts'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='address',
        ),
        migrations.AddField(
            model_name='userprofile',
            name='hometown',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='posts.City'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='job',
            field=models.CharField(default=datetime.datetime(2016, 2, 25, 0, 30, 29, 308578, tzinfo=utc), max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='userprofile',
            name='school',
            field=models.CharField(default=datetime.datetime(2016, 2, 25, 0, 30, 32, 400350, tzinfo=utc), max_length=50),
            preserve_default=False,
        ),
    ]
