# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-02-21 01:40
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0003_auto_20160221_0118'),
    ]

    operations = [
        migrations.AlterField(
            model_name='house',
            name='address',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='posts.Address'),
        ),
    ]
