# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-21 01:25
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0003_auto_20160221_0118'),
        ('posts', '0003_auto_20160221_0122'),
    ]

    operations = [
    ]
