# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-02-28 03:01
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0003_auto_20160225_0030'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='city_to',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='city_to', to='posts.City'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='hometown',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='hometown', to='posts.City'),
        ),
    ]
