# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-03-03 02:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0004_auto_20160228_0301'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='budget',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
