# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-02-21 03:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0007_auto_20160221_0305'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='tags',
            field=models.ManyToManyField(blank=True, through='posts.PostTag', to='posts.Tag'),
        ),
    ]
