# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-05 01:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0008_userprofile_age'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='picture',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
