# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-19 23:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0002_auto_20160119_1703'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='selected',
            field=models.BooleanField(default=False),
        ),
    ]
